### ISSUE TITLE
Ported to ESP32-Arduino

### ISSUE THREAD

**Issue by tobozo** [niklasekstrom/boing_ball_python#1]
Hey and thank you for your awesome project :-)

I created this issue just to let you know I used your script as a model to produce [C code for ESP32](https://github.com/tobozo/ESP32-BLECollector/blob/master/AmigaBall.h)

Here's a demo: https://youtu.be/_GrhF4i2eaY?t=5

With the flickering it looks more like the C64 version of the Amiga ball :)

**Comment by niklasekstrom** [comment]
Hey, that's excellent! Very nicely done, and thanks so much for letting me know about it. It seems I'm not alone in remembering the Amiga fondly :-)
